language: generic
services:
  - docker

before_install:
  - docker build -t suwigyarathore/complex-ci-cd-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true suwigyarathore/complex-ci-cd-react-test npm run test -- --coverage

after_success:
  - docker build -t suwigyarathore/complex-ci-cd-client ./client
  - docker build -t suwigyarathore/complex-ci-cd-nginx ./nginx
  - docker build -t suwigyarathore/complex-ci-cd-server ./server
  - docker build -t suwigyarathore/complex-ci-cd-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push suwigyarathore/complex-ci-cd-client
  - docker push suwigyarathore/complex-ci-cd-nginx
  - docker push suwigyarathore/complex-ci-cd-server
  - docker push suwigyarathore/complex-ci-cd-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'complex-ci-cd'
  env: 'Complexcicd-env'
  bucket_name: 'elasticbeanstalk-us-east-2-153157716099'
  bucket_path: 'complex-ci-cd'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY